#spring.application.name=ms-api-gateway

server:
  port: 9000

spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      routes:
      - id: ms-products-service-route
        uri: lb://ms-products-service
        predicates:
        - Path=/products/**
        filters:
        - name: CircuitBreaker # This is necessary to be this
          args:
            name: productFallbackController
            fallbackUri: forward:/fallback/products
#      - id: ms-fallback-products-service-route
#        uri: lb://ms-fallback-products-service
#        predicates:
#        - Path=/fallback/**

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
        - beans
  endpoint:
    health:
      group:
        system:
          show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productFallbackController:
        wait-duration-in-open-state: 15000
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Default value for eureka