#spring.application.name=ms-api-gateway

server:
  port: 9000

spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      routes:
      - id: ms-products-service-route
        uri: lb://ms-products-service
        predicates:
        - Path=/products/**
#      - id: adf
#        uri: adfa
#        predicates:
#        - Path=/recommendations/**
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Default value for eureka