server:
  port: 9003

spring:
  application:
    name: ms-products-service
  rabbitmq:
    host: localhost
    port: 5672
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Fallback in case one is not presented
      
# Names of the exchanges, topics, etc.

exchange:
  name: my-topic-exchange

topic:
  name: hello.#