server:
  port: 9010

spring:
  application:
    name: ms-recommendations-service
  rabbitmq:
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
exchange:
  name: my-topic-exchange
  
queue:
  name: my-queue
  routing-key: hello.world